const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
const DISCORD_TOKEN = process.env.DISCORD_TOKEN_EMOBOT;
const DISCORD_DEPLOYMENT_CHANNEL =
  process.env.DISCORD_DEPLOYMENT_CHANNEL_EMOBOT;

module.exports = {
  OPENAI_API_KEY,
  DISCORD_TOKEN,
  DISCORD_DEPLOYMENT_CHANNEL,
};
